# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[28,)"
# A list of mods
[[mods]]
# The moded of the mod
modId="japanese_food_mod"
# The version number of the mod
version="1.0.0"
# A display name for the mod
#displayName="Japanese Food Mod"
# A URL for the mod
#displayURL="" #optional
# A file name (in the root of the mod JAR9 containing a logo for display
logoFile="" #optional
# A text field displayed in the mod UI
authors="TDN"
# The description text for the mod (multi line)
description='''
    Add recipes and items for Japanese food.
'''
# A dependency - use the . to indicate dependency for a specific modid
[[dependencies.jp.tdn.japanese_food_mod]] #optional
    # the modid of the dependency
    modId="forge"
    # Does this dependency have to exist
    mandatory=true
    # The version range of the dependency
    versionRange="[28,)"
    # An ordering relationship for the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.jp.tdn.japanese_food_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"