# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[32,)"
# A list of mods
[[mods]]
modId="japanese_food_mod"
version="${file.jarVersion}"
#displayName="Japanese Food Mod"
#displayURL="" #optional
logoFile="logo.png" #optional
authors="TDN"
description='''
    Add recipes and items for Japanese food.'''

[[dependencies.jp.tdn.japanese_food_mod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.jp.tdn.japanese_food_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.jp.tdn.japanese_food_mod]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.1-37,)"
    side="BOTH"